### ISSUE TITLE
请解释你怎么创造了freq_dict.txt

### ISSUE THREAD

**Issue by ssb22** [fastcws/assets#1]
您好，多谢你出版这个分词系统。为了安慰大家这词库的质量和合法性，您会不会加个小解释你用什么方法创造了这个`freq_dict.txt`文件? 多谢。  Thank you for publishing fastcws.  To reassure everyone of the quality and legality of the wordbank, would you be able to add a brief description saying how you made the `freq_dict.txt` file?

**Comment by omegacoleman** [comment]
感谢关注，已通过 612c4d2 添加。此仓库中所有内容都来源于来源于 Wikipedia 。

Thanks, added via 612c4d2. All materials in this repo is originated from Wikipedia.
